name: smart
version: 0.0.1
description: A library for data driven analysis of Dart.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/smart

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
 analyzer: "^0.27.0"
 logging: "^0.11.0"
 cli_util: "^0.0.1"

dev_dependencies:
# change this to a specific version range when you create your project
  test: any
