name: smart
description: A library for data driven analysis of Dart.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/smart

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  appengine: ^0.3.0
  memcache: ^0.2.0
  googleapis_auth: '>=0.1.1 <0.3.0'
  gcloud: '>=0.2.0+4 <0.3.0'
  analyzer: "^0.27.0"
  logging: "^0.11.0"
  cli_util: "^0.0.1"
  crypto: "^0.9.1"
  trotter: "^0.8.1"

dev_dependencies:
  sintr_common:
    git: https://github.com/lukechurch/sintr_common.git
  test: any
